### PR TITLE
Issue 13 :: derive Jason.Encoder

### LINKED ISSUE #13: Better support for Jason library
If you use `jason` instead of `poison` for JSON encoding, you have to derive a serialization for `Airbrake.Payload`.  This is _not_ enough:

```
Protocol.derive(Jason.Encoder, Airbrake.Payload)
```

This is because `Airbrake.Payload` defines only a few fields in its struct: 

https://github.com/CityBaseInc/airbrake_client/blob/master/lib/airbrake/payload.ex#L10

However, the "enhanced options" for `Airbrake.report/2` include optional fields `:context`, `:params`, `:session`, and `:env`.  Since they are not part of the `Airbrake.Payload` struct, deriving `Jason.Encoder` ignores those fields, and you get anemic reports in Airbrake.io.

Here's how I verified the problem in an `iex` session:

```
iex(6)> payload = Airbrake.Payload.new([type: "TestingError", message: "Testing Airbrake.report/2"], [], context: %{
...(6)>   foo: "bar",
...(6)>   now: "America/Chicago" |> DateTime.now!() |> inspect()
...(6)> })
%{
  __struct__: Airbrake.Payload,
  apiKey: nil,
  context: %{
    environment: "dev",
    foo: "bar",
    hostname: "000045",
    now: "#DateTime<2021-06-04 11:43:51.448695-05:00 CDT America/Chicago>"
  },
  errors: [
    %{backtrace: [], message: "Testing Airbrake.report/2", type: "TestingError"}
  ],
  notifier: %{
    name: "Airbrake Client",
    url: "https://github.com/CityBaseInc/airbrake_client",
    version: "0.8.2"
  }
}
iex(8)> Jason.encode!(payload) |> Jason.decode()
{:ok,
 %{
   "apiKey" => nil,
   "errors" => [
     %{
       "backtrace" => [],
       "message" => "Testing Airbrake.report/2",
       "type" => "TestingError"
     }
   ],
   "notifier" => %{
     "name" => "Airbrake Client",
     "url" => "https://github.com/CityBaseInc/airbrake_client",
     "version" => "0.8.2"
   }
 }}
```

Adding these extra fields to the struct seems like a good idea, but I suspect then the fields will _always_ be sent to Airbrake.io, set to `nil` if a field hasn't been assigned a value.  This seems like it could lead to a lot of noise in the reports.  So _just_ adding the fields to the struct will not be sufficient.  (This might be a very easy problem to solve with options provided by `jason` and `poison`.)

Somewhat separately, it would be great if `airbrake_client` derived an encoding for `Airbrake.Payload` itself.  This was a good idea to begin with (rather than forcing anyone using the library to come up with their own encoded).  But if the encoding is more involved than just calling `Protocol.derive/2`, then for easy-of-use this library _must_ define the encoding, and it might as well be done fixing the missing struct fields.

### PR DESCRIPTION
**Pull request by jdfrens**
This PR fixes the `Airbrake.Payload` struct and derives `Jason.Encoder` for Airbrake.Payload`.  Closes #13.

## This Problem

Airbrake.io accepts a lot of fields in the payload for an error report.  However, `Airbrake.Payload` defined only three of them: 

https://github.com/CityBaseInc/airbrake_client/blob/6d0d16fad1abbd51ff0f6609a1f2be9411958d93/lib/airbrake/payload.ex#L10

Airbrake.io also accepts "context", "params", "session", and "environment" in the payload.  `Airbrake.Payload` adds values for those fields anyway, and `poison` was more than happy to encode them.  `jason` is more precise, and deriving the `Jason.Encoder` for `Airbrake.Payload` left those non-struct fields out.

Leaving out those fields also made it inevitable to get "field not defined on `Airbrake.Payload`" errors with recent versions of Elixir.

## The Fixes

This PR adds the missing fields to the `Airbrake.Payload` struct.
* This doesn't break `poison` at all.
* `Jason.Encoder` can be derived automatically (conditionally compiled).
* No more "field not defined" errors.

The only drawback is that if a field is not given a value, it is still included in the encoding, set to `null`.  Airbrake.io seems to ignore those fields, so `null` is not a problem for them.  It consumes a little more bandwidth, but not _that_ much.  (And devs should be encouraged to use all of the fields anyway.)

I greatly improved the testing around `Airbrake.Payload`.  I tried to keep each commit to one theme, and refactoring commits should have few (if any) test changes.

## Manual Tesing

I ran some tests, reporting "errors" into Airbrake.io.  You can see the errors I generated from my laptop (named `000045`):

* https://citybase.airbrake.io/projects/240982/groups/3026442380264171863?filters=%7B%22order%22%3A%22last_notice%22%2C%22resolved%22%3A%22false%22%2C%22context.environment%22%3A%22-2734551907716605563%22%7D&tab=overview

## More Testing

I added an `integration_test_apps` to make sure that the encodings work even when the app depends on just one app.  In particular, I wanted to make sure that deriving of `Jason.Encoder` happened only when `jason` was a dependency.

I don't expect these apps to fail, so they're probably not important to run locally all the time, but I did include them in the CI tests just in case.

### CODE REVIEW

File: integration_test_apps/jason_only_app/test/jason_only_app_test.exs [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+
+  test "Poison is undefined" do
+    # There is no conditional compilation for `poison`... yet.
+    refute Code.ensure_compiled(Poison) == {:module, Poison}
+  end
+
+  describe "Jason encoding" do
+    test "with minimal options" do
+      exception = [
+        type: "SomeAwfulError",
```
Comment (kyle-annen) [inline integration_test_apps/jason_only_app/test/jason_only_app_test.exs:14]: Nice naming!

**Review by kyle-annen — APPROVED** [review]
Looks great, nice use of property testing. First time seeing `StreamData`, big fan!

File: .github/workflows/test.yml [hunk 2]
```diff
@@ -38,6 +38,37 @@ jobs:
       - run: mix deps.get
       - run: mix test
 
+  poison_only_test:
```
Comment (gabrieltaylor) [inline .github/workflows/test.yml:41]: :heart:

**Review by gabrieltaylor — APPROVED** [review]
